##默认使用配置
#spring:
#  profiles:
#    active: dev
#
#---
#
##开发配置
#spring:
#  profiles: dev
#
#    datasource:
#      url: jdbc:mysql://localhost:3306/xiaomi?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true
#      username: root
#      password: cT;sEw#-w49f
#      driver-class-name: com.mysql.jdbc.Driver
#      # 使用druid数据源
#      type: com.alibaba.druid.pool.DruidDataSource
#
#
#
#    #redis
#    redis:
#      host: 127.0.0.1
#      port: 6379
#      password:
#      pool:
#        max-idle: 8
#        min-idle: 0
#        max-active: 8
#        max-wait: -1
#      database: 0
#
#    rabbitmq:
#      host: 127.0.0.1
#      port: 5672
#      username: guest
#      password: guest
#      publisher-confirms: true    #  消息发送到交换机确认机制,是否确认回调
#
#
#  logging:
#    config: classpath:log4j2.yml
#
